apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-server
  template:
    metadata:
      labels:
        app: etcd-server
    spec:
       containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.0
          command:
          - etcd
          - "--advertise-client-urls"
          - "http://etcd:2379"
          - "--listen-client-urls"
          - "http://0.0.0.0:2379"
          ports:
          - containerPort: 2379
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-service
spec:
  selector:
    app: etcd
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379
