apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_DATABASE
              value: messaging_service
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: init-sql
              mountPath: /data/application/init.sql
              subPath: init.sql
      volumes:
        - name: mysql-data
          emptyDir: {}
        - name: init-sql
          configMap:
            name: init-sql-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: imdb
spec:
  selector:
    app: mysql
    tier: database
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3306
